FROM node:10.12.0

WORKDIR /usr/src/app
RUN npm install -g nodemon
COPY package*.json /usr/src/app/
RUN npm install && mv /usr/src/app/node_modules /node_modules
COPY . /usr/src/app

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
